# Generated by Django 5.1.3 on 2024-11-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workflow",
            new_name="Work",
        ),
    ]
