# Generated by Django 5.1.3 on 2024-11-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_workflow_work"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="Problem",
            new_name="problem",
        ),
        migrations.AlterField(
            model_name="work",
            name="image",
            field=models.ImageField(upload_to="works/"),
        ),
        migrations.CreateModel(
            name="WorkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="work_images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.work",
                    ),
                ),
            ],
        ),
    ]
