# Generated by Django 5.1.3 on 2024-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_problem_work_problem_alter_work_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="type",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
